# Generated by Django 4.2.7 on 2024-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=500)),
                ('password1', models.CharField(max_length=500)),
                ('password2', models.CharField(max_length=500)),
            ],
        ),
    ]
