# Generated by Django 4.2.7 on 2024-12-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUserForm',
            new_name='Form',
        ),
    ]
