# Generated by Django 4.2.7 on 2024-12-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_password1_form_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
