# Generated by Django 4.2.7 on 2024-12-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_title_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='title',
            new_name='header',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='blogs.name'),
        ),
    ]
