# Generated by Django 4.2.7 on 2024-12-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_name_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='head',
        ),
    ]
