# Generated by Django 4.2.7 on 2024-12-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_title_blog_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='head',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
