# Generated by Django 4.2.7 on 2025-01-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='user',
            new_name='userid',
        ),
    ]
