# Generated by Django 4.2.7 on 2025-01-10 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_rename_userid_useractivity_usernameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='commented_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
